# Generated by Django 4.2 on 2023-06-04 04:03

import account.base
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artist",
            name="photo",
            field=models.ImageField(upload_to=account.base.category_image_dir_path),
        ),
        migrations.AlterField(
            model_name="artist",
            name="ward",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="normaluser",
            name="photo",
            field=models.ImageField(upload_to=account.base.category_image_dir_path),
        ),
        migrations.AlterField(
            model_name="normaluser",
            name="ward",
            field=models.PositiveIntegerField(),
        ),
    ]
