# Generated by Django 4.2 on 2024-02-24 04:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0002_alter_artist_photo_alter_artist_ward_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artist",
            name="contact",
            field=models.BigIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "((98)|(97))(\\d){8}",
                        message="Invalide data to the fields......",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="normaluser",
            name="contact",
            field=models.BigIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "((98)|(97))(\\d){8}",
                        message="Invalide data to the fields......",
                    )
                ],
            ),
        ),
    ]
