# Generated by Django 4.2 on 2023-12-09 06:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="ticket_no",
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
