# Generated by Django 4.2 on 2023-12-10 08:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0002_ticket_ticket_no"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticket",
            name="price",
        ),
        migrations.AlterField(
            model_name="ticket",
            name="ticket_no",
            field=models.PositiveBigIntegerField(default=1),
        ),
    ]
