# Generated by Django 4.2 on 2023-12-10 15:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0003_remove_ticket_price_alter_ticket_ticket_no"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="booked_by",
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
