# Generated by Django 4.2 on 2023-12-10 16:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0005_remove_ticket_id_alter_ticket_ticket_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="ticket_no",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
