# Generated by Django 4.2 on 2023-12-10 16:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("emsadmin", "0018_alter_sponser_photo"),
        ("booking", "0006_alter_ticket_ticket_no"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticket",
            name="event",
        ),
        migrations.AddField(
            model_name="ticket",
            name="event",
            field=models.ManyToManyField(to="emsadmin.event"),
        ),
    ]
