# Generated by Django 4.2 on 2023-12-10 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("emsadmin", "0019_alter_sponser_photo"),
        ("booking", "0007_remove_ticket_event_ticket_event"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticket",
            name="event",
        ),
        migrations.AddField(
            model_name="ticket",
            name="event",
            field=models.ForeignKey(
                default=3,
                on_delete=django.db.models.deletion.CASCADE,
                to="emsadmin.event",
            ),
            preserve_default=False,
        ),
    ]
