# Generated by Django 4.2 on 2023-12-11 17:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0008_remove_ticket_event_ticket_event"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ticket",
            old_name="ticket_no",
            new_name="ticket_id",
        ),
        migrations.AddField(
            model_name="ticket",
            name="ticket_num",
            field=models.CharField(default=2, max_length=10000),
            preserve_default=False,
        ),
    ]
