# Generated by Django 4.2 on 2023-10-11 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Heading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("heading", models.CharField(max_length=100)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Content_Management",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                ("updated_by", models.CharField(max_length=10)),
                (
                    "status",
                    models.CharField(
                        choices=[("Draft", "draft"), ("Publish", "publish")],
                        max_length=100,
                    ),
                ),
                (
                    "heading",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="content_management.heading",
                    ),
                ),
            ],
        ),
    ]
