# Generated by Django 4.2 on 2024-03-14 12:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content_management", "0002_blog"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="updated_by",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
