# Generated by Django 4.2 on 2024-03-16 04:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content_management", "0003_blog_updated_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="created_by",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
