# Generated by Django 4.2 on 2024-03-22 04:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content_management", "0004_alter_blog_created_by"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("data_created", models.DateTimeField(auto_now_add=True)),
                ("data_updated", models.DateTimeField(auto_now=True)),
                ("blog", models.ManyToManyField(to="content_management.blog")),
            ],
        ),
    ]
