# Generated by Django 4.2 on 2024-03-22 04:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content_management", "0005_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="title",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
