# Generated by Django 4.2 on 2024-03-22 05:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content_management", "0006_blog_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="like",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="comment",
            name="blog",
            field=models.ManyToManyField(
                blank=True, null=True, to="content_management.blog"
            ),
        ),
    ]
