# Generated by Django 4.2 on 2024-03-22 07:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content_management", "0008_remove_comment_blog_comment_blog"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
