# Generated by Django 4.2 on 2023-09-28 12:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("emsadmin", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="sponser",
        ),
        migrations.AddField(
            model_name="event",
            name="sponser",
            field=models.ManyToManyField(to="emsadmin.sponser"),
        ),
    ]
