# Generated by Django 4.2 on 2023-10-11 09:52

from django.db import migrations, models
import emsadmin.models


class Migration(migrations.Migration):
    dependencies = [
        ("emsadmin", "0002_remove_event_sponser_event_sponser"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to=emsadmin.models.category_image_dir_path
            ),
        ),
    ]
