# Generated by Django 4.2 on 2023-10-11 09:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("emsadmin", "0003_event_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="sponser",
            field=models.ManyToManyField(blank=True, null=True, to="emsadmin.sponser"),
        ),
    ]
