# Generated by Django 4.2 on 2023-12-07 06:45

from django.db import migrations, models
import emsadmin.models


class Migration(migrations.Migration):
    dependencies = [
        ("emsadmin", "0005_alter_event_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="sponser",
            name="photo",
            field=models.ImageField(
                blank=True,
                upload_to="",
                verbose_name=emsadmin.models.category_image_dir_path,
            ),
        ),
    ]
