# Generated by Django 4.2 on 2023-12-12 07:33

from django.db import migrations, models
import emsadmin.models


class Migration(migrations.Migration):
    dependencies = [
        ("emsadmin", "0021_alter_sponser_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="remaining_capacity",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sponser",
            name="photo",
            field=models.ImageField(
                blank=True, upload_to=emsadmin.models.category_image_dir_path
            ),
        ),
    ]
