# Generated by Django 4.2 on 2023-12-18 10:42

from django.db import migrations, models
import emsadmin.models


class Migration(migrations.Migration):
    dependencies = [
        ("emsadmin", "0022_event_remaining_capacity_alter_sponser_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="no_of_participant",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="sponser",
            name="photo",
            field=models.ImageField(
                blank=True, upload_to=emsadmin.models.category_image_dir_path
            ),
        ),
    ]
