# Generated by Django 4.2 on 2024-03-02 16:34

from django.db import migrations, models
import emsadmin.models


class Migration(migrations.Migration):
    dependencies = [
        ("emsadmin", "0039_alter_sponser_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="genres",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Pop", "Pop"),
                    ("Rock", "Rock"),
                    ("Melody", "Medoly"),
                    ("Hiphop/Rap", "Hiphop/Rap"),
                    ("Electronic/Dance", "Electronic/Dance"),
                    ("Intie/Alternative", "Intie/Alternative"),
                    ("R&B/Soul", "R&B/Soul"),
                    ("Country", "Country"),
                    ("Jazz", "Jazz"),
                    ("Classical", "Classical"),
                    ("Old/Ethic", "Old/Ethic"),
                ],
                max_length=1000,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="sponser",
            name="photo",
            field=models.ImageField(upload_to=emsadmin.models.category_image_dir_path),
        ),
    ]
