# Generated by Django 4.2 on 2024-03-14 12:20

from django.db import migrations, models
import emsadmin.models


class Migration(migrations.Migration):
    dependencies = [
        ("emsadmin", "0042_alter_sponser_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sponser",
            name="photo",
            field=models.ImageField(upload_to=emsadmin.models.category_image_dir_path),
        ),
    ]
