# Generated by Django 4.2 on 2024-03-15 09:14

from django.db import migrations, models
import emsadmin.models


class Migration(migrations.Migration):
    dependencies = [
        ("emsadmin", "0043_alter_sponser_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[("Accept", "Accept"), ("Request", "Request")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="sponser",
            name="photo",
            field=models.ImageField(upload_to=emsadmin.models.category_image_dir_path),
        ),
    ]
